<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petrinet" nsURI="http://petrinet" nsPrefix="petrinet">
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//CaseElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokens" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//CaseElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Arc" eSuperTypes="#//NetworkElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readOnly" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkToPrevCase" lowerBound="1"
        eType="#//CaseElement" eOpposite="#//CaseElement/linksToNextArcs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkToNextCase" eType="#//CaseElement"
        eOpposite="#//CaseElement/linksToPrevArcs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Network">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="networkElements" upperBound="-1"
        eType="#//NetworkElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NetworkElement" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="CaseElement" abstract="true" eSuperTypes="#//NetworkElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksToPrevArcs" upperBound="-1"
        eType="#//Arc" eOpposite="#//Arc/linkToNextCase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linksToNextArcs" upperBound="-1"
        eType="#//Arc" eOpposite="#//Arc/linkToPrevCase"/>
  </eClassifiers>
</ecore:EPackage>
