<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="algo" nsURI="http://www.example.org/algo" nsPrefix="algo">
  <eClassifiers xsi:type="ecore:EClass" name="Algo" eSuperTypes="#//Documentable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ressource" lowerBound="1"
        eType="#//Ressource" containment="true" eOpposite="#//Ressource/algo"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" lowerBound="1"
        eType="#//Flux" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Flux" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="documentations" upperBound="-1"
        eType="#//Documentation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ressource" eSuperTypes="#//Documentable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="algo" lowerBound="1" eType="#//Algo"
        eOpposite="#//Algo/ressource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flux" eSuperTypes="#//Documentable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DataType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Documentable" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Documentation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commentaire" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkToElement" lowerBound="1"
        eType="#//Documentable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="string"/>
    <eLiterals name="int" value="1"/>
    <eLiterals name="bool" value="2"/>
    <eLiterals name="float" value="3"/>
  </eClassifiers>
</ecore:EPackage>
